# Generated by Django 4.2.9 on 2024-11-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
