# Generated by Django 4.2.9 on 2024-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0002_uploadedimage_age_uploadedimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='--------', max_length=10),
        ),
    ]
