# Generated by Django 4.2.9 on 2024-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0003_uploadedimage_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='gender',
            field=models.CharField(choices=[('', '--------'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=10),
        ),
    ]
