# Generated by Django 4.2.9 on 2024-12-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0004_alter_uploadedimage_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='4671 Sugar Camp Road, Owatonna, Minnesota, 55060', max_length=255, verbose_name='Address')),
                ('phone', models.CharField(default='571-457-2321', max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(default='ntamerrwael@mfano.ga', max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
    ]
