# Generated by Django 4.2.9 on 2024-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0005_contactinfo_alter_uploadedimage_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(default='2nd Flr, Chaudhary Plaza, Rawalpindi', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='admin@info.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='+92-331-6262-363', max_length=15, verbose_name='Phone'),
        ),
    ]
