# Generated by Django 4.2.9 on 2024-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0007_alter_contactinfo_phone_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author'),
        ),
    ]
