# Generated by Django 4.2.9 on 2025-04-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0015_contactmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='lung_disease.doctorprofile'),
        ),
    ]
