# Generated by Django 4.2.9 on 2025-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_disease', '0016_patientprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor Name'),
        ),
    ]
