# Generated by Django 4.2.9 on 2025-05-05 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lung_disease', '0017_patientprofile_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor_comment',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='needs_doctor_assistance',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('prediction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prediction Result')),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor Name')),
                ('doctor_comment', models.TextField(blank=True, null=True)),
                ('needs_doctor_assistance', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='lung_disease.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lung_disease.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
