# Generated by Django 4.2.9 on 2025-05-05 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lung_disease', '0018_remove_patientprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='lung_disease.doctorprofile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor Name'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(default='uploads/x_normal.png', upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='needs_doctor_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='prediction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prediction Result'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Uploaded At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PatientReport',
        ),
    ]
